; Module info

name             = Text-Conflux
author           = Richard M. Loveland <r@rmloveland.com>
license          = Perl_5
copyright_holder = Richard M. Loveland <r@rmloveland.com>
copyright_year   = 2018
version          = 0.01

[@Basic]

[AutoPrereqs]
[PodSyntaxTests]
[PodCoverageTests]
[Test::Perl::Critic]

[MetaResources]
homepage        = https://metacpan.org/module/Text::Conflux
repository.web  = https://github.com/rmloveland/Text-Conflux
repository.url  = https://github.com/rmloveland/Text-Conflux.git
repository.type = git

; Release

[TestRelease]
[ConfirmRelease]
[UploadToCPAN]
